---
LEFT:
    hostname: "192.168.227.231"
    username: "cisco"
    password: "cisco"
    groups:
        - cisco_group

MIDDLE:
    hostname: "192.168.227.232"
    username: "cisco"
    password: "cisco"
    groups:
        - cisco_group

RIGHT:
    hostname: "192.168.227.233"
    username: "cisco"
    password: "cisco"
    groups:
        - cisco_group