---
R1:
    hostname: "192.168.227.231"
    groups:
        - cisco_group

R2:
    hostname: "192.168.227.232"
    groups:
        - cisco_group

R3:
    hostname: "192.168.227.233"
    groups:
        - cisco_group
